
services:
  web:
    image: windy007008/web_tt_ss_n:latest
    restart: always
    ports:
      - "5003:5003"
    volumes:
      - ./user_data:/app/user_data
      - ./cache:/app/cache
      - ./backup:/app/backup
      - ./chrome_data:/app/chrome_data
      # - /etc/letsencrypt/live/windy.run/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      # - /etc/letsencrypt/live/windy.run/privkey.pem:/etc/ssl/certs/privkey.pem:ro
   
    environment:
      - HTTP_PROXY=http://host.docker.internal:10809
      - HTTPS_PROXY=http://host.docker.internal:10809
      - http_proxy=http://host.docker.internal:10809
      - https_proxy=http://host.docker.internal:10809
      - FLASK_ENV=production
    user: "1000:1000"  # 使用宿主机的UID:GID
    command: ["gunicorn", 
              "--workers", "4",
              "--timeout", "120",
              "--keep-alive", "5",
              "--max-requests", "1000",
              "--max-requests-jitter", "50",
              "--log-level", "debug",        # 改为 error/debug 级别
              "--access-logfile", "-",
              "--error-logfile", "-",
                # "--certfile", "/etc/ssl/certs/fullchain.pem",  # 添加 SSL 证书配置

                # "--keyfile", "/etc/ssl/certs/privkey.pem",     # 添加 SSL 密钥配置
              "--bind", "0.0.0.0:5003",
              "--access-logformat", "%(h)s %(l)s %(u)s %(t)s '%(r)s' %(s)s %(b)s '%(f)s' '%(a)s'",  # 添加自定义日志格式
              "app:app"]
