
services:
  web:
    build: .
    image: windy007008/web_tt_ss_n:latest
    ports:
      - "5003:5003"  
    volumes:
      - ./user_data:/app/user_data
      - ./cache:/app/cache
      - ./backup:/app/backup
      - ./chrome_data:/app/chrome_data
    environment:
      - HTTP_PROXY=http://host.docker.internal:10809
      - HTTPS_PROXY=http://host.docker.internal:10809
      - http_proxy=http://host.docker.internal:10809
      - https_proxy=http://host.docker.internal:10809
      - FLASK_ENV=development  # 标记为开发环境
    restart: always
    user: "1000:1000"  # 使用宿主机的UID:GID
    command: ["gunicorn", 
              "--workers", "4",
              "--timeout", "120",
              "--keep-alive", "5",
              "--max-requests", "1000",
              "--max-requests-jitter", "50",
              "--log-level", "debug",     # 开发环境使用 debug 级别
              "--access-logfile", "-",
              "--error-logfile", "-",
              "--bind", "0.0.0.0:5003",
              "app:app"]


